package com.example.rule.model;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
@TableName("fm_rtrecord")
public class MSEvent implements Serializable {
    @TableField(exist = false)
    private static final long serialVersionUID = 1L;
    @TableField(exist = false)
    private OperationType operationType = OperationType.INSERT;
    @TableField(exist = false)
    private String subOperationType = "";
    // ------------ 基本信息 ------------
    @TableId
    private Long recordId;
    private String eventId;
    private String objectId;
    private String sourceId;
    private String keyValue;
    private String descr;
    private int counts;
    private Date startTime;
    private Date lastTime;
    private Date occurTime;
    private Date discoverTime;
    private Date saveTime;
    private int ackTag;
    private String ackUser;
    private Date ackTime;
    private int clearTag;
    private String clearUser;
    private Date clearTime;
    private long restoreId;
    private int restoreTag;
    private Date restoreTime;
    private int inheritTag;
    private int dispTag;
    private String dispUser;
    private Date dispTime;
    private String dispRules;
    private String dispFaultCause;
    private String dispUndoCause;
    private String dispId;
    private String dispStatus;
    private Date dispSyncTime;
    private String sourceSystem;
    private Date sourceStartTime;
    private Date sourceEndTime;
    private String sourceName;
    private int projectStatus;
    private String projectStatusSub;
    private String projectName;
    private String projectId;
    private Date projectStartTime;
    private Date projectEndTime;
    private int errorTag;
    private String errorInfo;
    private int reportTag;
    private String collectionType;
    private String faultProbableCause;
    private int remarkTag;
    private String remark;
    private long paras1;
    private long paras2;
    private long paras3;
    private long paras4;
    private long paras5;
    private long paras6;
    private long paras7;
    private long paras8;
    private long paras9;
    private long paras10;
    private long paras11;
    private long paras12;
    private long paras13;
    private long paras14;
    private long paras15;
    private long paras16;
    private long paras17;
    private long paras18;
    private long paras19;
    private long paras20;
    private String parasa;
    private String parasb;
    private String parasc;
    private String parasd;
    private String parase;
    private String parasf;
    private String parasg;
    private String parash;
    private String parasi;
    private String parasj;
    private String parask;
    private String parasl;
    private String parasm;
    private String parasn;
    private String paraso;
    private String parasp;
    private String parasq;
    private String parasr;
    private String parass;
    private String parast;
    private String parasu;
    private String parasv;
    private String parasw;
    private String parasx;
    private String parasy;
    private String parasz;
    // ------------ 对象信息 ------------
    private String objectName;
    private String objectAlias;
    private String objectIp;
    private String objectDesc;
    private String objectType;
    private String deviceId;
    private String deviceName;
    private String deviceAlias;
    private String deviceIp;
    private String deviceSpecialty;
    private String deviceSpecialtySub;
    private String deviceService;
    private String deviceServiceSub;
    private String deviceNetwork;
    private String deviceNetworkSub;
    private String deviceNetworkLevel;
    private String deviceLocation;
    private String deviceType;
    private String deviceVersion;
    private String deviceDesc;
    private String deviceVendor;
    private String deviceProvince;
    private String deviceCity;
    private String deviceCounty;
    private String deviceSite;
    private String deviceSiteLevel;
    private String deviceRoom;
    private String property1;
    private String property2;
    private String property3;
    private String property4;
    private String property5;
    private String property6;
    private String property7;
    private String property8;
    private String property9;
    private String property10;
    private String property11;
    private String property12;
    private String property13;
    private String property14;
    private String property15;
    // ------------ 事件信息 ------------
    private String vendorEventId;
    private String vendorEventFacl;
    private String vendorEventSeve;
    private String title;
    private String name;
    private int severity;
    private String comments;
    private int facility;
    private String facilityLogic;
    private String facilityLogicSub;
    private String referenceDevice;
    private String referenceService;
    private int harvestType;
    private String category;
    private int isReport;
    private String event1;
    private String event2;
    private String event3;
    private String event4;
    private String event5;
    private String property16;
    private String property17;
    private String property18;
    private String property19;
    private String property20;
    private String property21;
    private String property22;
    private String property23;
    private String property24;
    private String property25;
    private String property26;
    private String property27;
    private String property28;
    private String property29;
    private String property30;
    private String property31;
    private String property32;
    private String property33;
    private String property34;
    private String property35;
    private String property36;
    private String property37;
    private String property38;
    private String property39;
    private String property40;
    private String property41;
    private String property42;
    private String property43;
    private String property44;
    private String property45;
}